### ISSUE TITLE
Forwarder Issues, Spirit Tracks, 100 Classic Books

### ISSUE THREAD

**Issue by SgtMooshroom** [TWLBot/Builds#1]
Using the latest versions of TWiLightMenu++, nds-bootstrap, and HiyaCFW, attempting to launch Spirit Tracks or 100 Classic Books through a forwarder triggers the AP, meaning the patch isn't being applied when using a forwarder. They work just fine when launched directly from TWiLightMenu++, just not through a forwarder in HiyaCFW.

I've verified my ROM dumps through the Redump MD5 hash database. The hashes match, meaning the dumps are perfect.

**Comment by RocketRobz** [comment]
Please join this server for support: https://discord.gg/yD3spjv
The TWLBot repo is not the place to report issues.
